# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4546da7b487ba6f39dd5c36aaddb59c187ed31e041f30c69d0d2a9579344679c5bbe8d074c1006e50475e98f9d905a5d88b711c562a7e07b30468a7f04e89a79

test:
  secret_key_base: 63a36e21603c038dc9d49d1a723d2d5c1fe258539775bc6bb13fc0d6455fda86a381bf9af29b0358c23b4cae44ae126b36fe20db9b38d7ec331592d6a31c9df8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
